### ISSUE TITLE
Sample does not build with ncs v2.6.1

### ISSUE THREAD

**Issue by eechen-goldmine** [mjaakkol/multicore#1]
Tried to build the multicore sample with ncs v2.6.1 (Zephyr 3.5.99).

Error in `netcore/src/main.c`

```
multicore/netcore/src/main.c:383:49: note: in expansion of macro 'DEVICE_DT_GET'
  383 |         const struct device *hci_ipc_instance = DEVICE_DT_GET(DT_CHOSEN(zephyr_bt_hci_rpmsg_ipc));
      |                                                 ^~~~~~~~~~~~~
```

This would appear to be because the name of the chosen label has changed to `zephyr_bt_hci_ipc`, from `zephyr_bt_hci_rpmsg_ipc` as a result of [this commit](https://github.com/zephyrproject-rtos/zephyr/commit/9cf07bbdb55f4264062297d2bee00779c7627604).

I've done a little fix to `netcore/src/main.c` in my local copy by detecting Zephyr version, and then choosing the appropriate name, but not sure if this should is the proper approach:

```
#include <zephyr/logging/log_ctrl.h>
#include <zephyr/logging/log.h>

#include <version.h>

...

#if KERNEL_VERSION_NUMBER >= ZEPHYR_VERSION(3, 5, 0)
#define CHOSEN_HCI_IPC zephyr_bt_hci_ipc
#else
#define CHOSEN_HCI_IPC zephyr_bt_hci_rpmsg_ipc
#endif

...

int main(void)
{
       int err;

       printk("netcore: build time: " __DATE__ " " __TIME__ "\n");

       const struct device *hci_ipc_instance = DEVICE_DT_GET(DT_CHOSEN(CHOSEN_HCI_IPC));
```

**Comment by mjaakkol** [comment]
Thanks for opening this. I fixed it per SDK 2.6.x and higher approach (no conditional compilation). This issue will show the old way of doing things if anybody needs to work with the older version of SDK.
